export const jobTypes = {
  FETCH_LIVE_JOB_START: "FETCH_LIVE_JOB_START",
  FETCH_LIVE_JOB_SUCCESS: "FETCH_LIVE_JOB_SUCCESS",
  FETCH_LIVE_JOB_FAILURE: "FETCH_LIVE_JOB_FAILURE",
  FETCH_ACCEPTED_JOB_START: "FETCH_ACCEPTED_JOB_START",
  FETCH_ACCEPTED_JOB_SUCCESS: "FETCH_ACCEPTED_JOB_SUCCESS",
  FETCH_ACCEPTED_JOB_FAILURE: "FETCH_ACCEPTED_JOB_FAILURE",
  FETCH_REJECTED_JOB_START: "FETCH_REJECTED_JOB_START",
  FETCH_REJECTED_JOB_SUCCESS: "FETCH_REJECTED_JOB_SUCCESS",
  FETCH_REJECTED_JOB_FAILURE: "FETCH_REJECTED_JOB_FAILURE",
  ADD_ACCEPTED_JOB_START: "ADD_ACCEPTED_JOB_START",
  ADD_REJECTED_JOB_START: "ADD_REJECTED_JOB_START",
};
